### ISSUE TITLE
[!] No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by minikin** [fulldecent/FDTake#101]
`To run the example project, clone the repo, and run pod install from the Example directory first.`
And we have:
`/FDTake/iOS Example/ (master) pod install
[!] No`Podfile' found in the project directory.`

**Comment by fulldecent** [comment]
I believe the `pod install` step is no longer necessary.

Are you able to clone the repo and open the workspace directly?

**Comment by fulldecent** [comment]
I believe this solves the problem. Please reopen if this is still an issue.
