### ISSUE TITLE
xCode 10 multiple command produce

### ISSUE THREAD

**Issue by havebeenfitz** [fulldecent/FDTake#112]
Hello, I'm having this issue with the new xcode.

`
Showing All Messages
-1: Multiple commands produce 'Products/Dev-iphonesimulator/FDTake/FDTake.framework/Info.plist':
1) Target 'FDTake' (project 'Pods') has copy command from '.../FDTake/Source/Info.plist' to '/.../Build/Products/Dev-iphonesimulator/FDTake/FDTake.framework/Info.plist'
2) Target 'FDTake' (project 'Pods') has process command with output '/...Build/Products/Dev-iphonesimulator/FDTake/FDTake.framework/Info.plist'
`

It's doubling plist files. THe issue can be resolved by deleting corresponding plist from the pod target. But with each pod install or xcode launch it switches back to previous state. Could you please take a look?

**Comment by abdulla-allaith** [comment]
+1

**Comment by GalaevAlexey** [comment]
same here

**Comment by abdulla-allaith** [comment]
is this library abandoned?! @fulldecent

**Comment by fulldecent** [comment]
This library is actively used. I just have not used it on the latest Xcode yet. Feedback and pull requests welcome. I personally am preparing for a conference and cannot look at this.

**Comment by LivioGama** [comment]
In the meantime, does anybody knows any alternative to this library?

**Comment by LivioGama** [comment]
Checking version 2.0.1

**Comment by LivioGama** [comment]
I have 
Showing All Errors Only
:-1: Multiple commands produce '/Users/livio/Library/Developer/Xcode/DerivedData/CloseUp-aliasnfsttlvqrdgagsqskjwjoww/Build/Products/Debug-iphonesimulator/FDTake/FDTake.framework/Info.plist':
1) Target 'FDTake' (project 'Pods') has copy command from '/Users/livio/Documents/closeup-ios/Pods/FDTake/Source/Info.plist' to '/Users/livio/Library/Developer/Xcode/DerivedData/App-aliasnfsttlvqrdgagsqskjwjoww/Build/Products/Debug-iphonesimulator/FDTake/FDTake.framework/Info.plist'

2) Target 'FDTake' (project 'Pods') has process command with output '/Users/livio/Library/Developer/Xcode/DerivedData/App-aliasnfsttlvqrdgagsqskjwjoww/Build/Products/Debug-iphonesimulator/FDTake/FDTake.framework/Info.plist'

**Comment by havebeenfitz** [comment]
I'm using release version of Xcode 10 and beta 1.6.0 of cocoapods

**Comment by LivioGama** [comment]
@fulldecent indeed the fix is simple : in the library build settings > build phase, you just remove Info.plist then it compiles. Alternatively : go on the Info.plist, uncheck the target membership and it will compile.

**Comment by fulldecent** [comment]
For me this is already off

![screen shot 2018-10-22 at 8 03 38 pm](https://user-images.githubusercontent.com/382183/47326203-a682c980-d635-11e8-82a9-f21acb32578d.png)

My test case is using the project and example app directly.

**Comment by LivioGama** [comment]
So it has to do with the way the library is build on cocoapods because on the pod install it's definitely checked 
![capture d ecran 2018-10-23 a 10 05 10](https://user-images.githubusercontent.com/6930498/47345538-475f9c00-d6ab-11e8-8af0-eeaa050a1f3c.png)

**Comment by emirbeytekin** [comment]
not workin xcode 10

**Comment by fulldecent** [comment]
Can anybody please confirm if this issue affects consumers using the Carthage integration method?

**Comment by fulldecent** [comment]
It seems this issue only affects pre-release configurations on Xcode + CocoaPods. Closing issue for now. Please reopen if non-CocoaPods targets are affected.

Updated documentation to state this policy: 81ab765

**Comment by LivioGama** [comment]
I'm using release version of Xcode 10 and release 1.5.2 of cocoapods. Not sure it's related to pre-release

**Comment by fulldecent** [comment]
Right now Xcode 10 not listed as a support version from CocoaPods as per https://cocoapods.org.
