### ISSUE TITLE
CocoaPods 2.0.2 version

### ISSUE THREAD

**Issue by LaserPatrick** [fulldecent/FDTake#114]
Hi, may you push the 2.0.2 version on CocoaPods? THX

**Comment by fulldecent** [comment]
Cannot push. The pod fails on Xcode 10 -- https://github.com/fulldecent/FDTake/issues/112

CocoaPods does not support Xcode 10 yet -- https://github.com/CocoaPods/CocoaPods/issues/8238

**Comment by fulldecent** [comment]
Published to CocoaPods with the latest version

https://github.com/fulldecent/FDTake/releases/tag/3.0.0
