### ISSUE TITLE
iPad landscape problems

### ISSUE THREAD

**Issue by kaspernissen** [fulldecent/FDTake#35]
On iPad this pod is working fine in portrait mode, however when presenting the popover controller in landscape mode the camera view is still in portrait. Taking a picture in landscape mode with the viewfinder in portrait, sets the image correct in landscape. So the problem is only occurring while finding your target.

From what i can find on google, maybe this is a Apple thing with the UIImagePickerController.

**Comment by fulldecent** [comment]
There has been a large rewrite committed to master. Is anyone able to confirm that this is fixed with the new version?

**Comment by fulldecent** [comment]
Closing now, please reopen if not working on latest version
