### ISSUE TITLE
[Issue] w/ delegate using CocoaPods

### ISSUE THREAD

**Issue by A1iAshoor** [fulldecent/FDTake#52]
If not using the static library (cocoapods), the delegate can get fired only ONCE, which is the first photo capture:
- (void)takeController:(FDTakeController *)controller gotPhoto:(UIImage *)photo withInfo:(NSDictionary *)info

*BUT*

If using FDTake static library (copy/paste), delegate got fired everytime I take new photo.

**Comment by fulldecent** [comment]
Closing as the latest version does not use delegate.

Please see the version in master which now uses callbacks
