### ISSUE TITLE
Localisation lost after switching to pods using frameworks

### ISSUE THREAD

**Issue by cakper** [fulldecent/FDTake#55]
Hello,

I've recently changed way my pods are installed (added ```use_frameworks!``` flag) and now strings are not localised (just getting standard keys like ```chooseFromLibrary```).
Is there a problem on my side or something that I need to change in the library?
I'm happy to prepare a PR if you let me know where this needs to be fixed.

Thanks, Kacper.

**Comment by fulldecent** [comment]
I haven't used pods yet with Swift. Here is another related issue https://github.com/Quick/Nimble/issues/104

I hope there is an expert that can provide more advice here.

**Comment by AnthonyMDev** [comment]
+1 Same issue here.
Cocoa pods now has Swift support.
If I have some extra time this weekend, I can look into making this work with Swift frameworks. No promises though. :P

**Comment by cakper** [comment]
@AnthonyMDev I didn't have much time to look into it, for now I manually set text properties on the controller itself
