### ISSUE TITLE
Support being initiated from a UIBarButtonItem on iPad

### ISSUE THREAD

**Issue by sindresorhus** [fulldecent/FDTake#56]
Currently it will show both the `UIActionSheet` and `UIPopoverController` at the top left of the screen on iPad. This is because `UIBarButtonItem` inherits from `NSObject` instead of `UIView` because of legacy...

Found this code snippet somewhere for `UIPopoverController`:

```objective-c
if ([sender isKindOfClass:[UIBarButtonItem class]]) {
  [popoverController presentPopoverFromBarButtonItem:sender permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
} else {
  [popoverController presentPopoverFromRect:((UIView *)sender).bounds inView:sender permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
}
```

For `UIActionSheet` you need to use `showFromBarButtonItem`:

```objective-c
[self.actionSheet showFromBarButtonItem:self.barButtonItem animated:YES];
```

-

Can you also change to use the `sender` by default instead of us having to manually set it?

-

I would do a pull request, but I'm a total beginner with Objective-C.

**Comment by fulldecent** [comment]
Does this solution work for everyone else?

**Comment by sindresorhus** [comment]
I tried it out from a UIBarButtonItem (that is located on the bottom of the screen) on iPad and it works correctly for the first UIActionSheet with the "Choose from Library" button, but when I tap that button it opens the next UIActionSheet with the actual image picker at the top of the screen, instead of bottom where the original UIActionSheet and UIBarButtonItem is.
