### ISSUE TITLE
Black screen if user did not allow app to access the camera

### ISSUE THREAD

**Issue by duc-dws** [fulldecent/FDTake#63]
- Choose "Take photo".
- App asks for permission.
- Choose "Do not allow".
- Camera appears with black screen.

**Comment by adeem** [comment]
I would suggest that we have two call backs (delegate)
- Camera access denied 
- Photo gallery access denied

**Comment by fulldecent** [comment]
I like this solution with delegates

**Comment by fulldecent** [comment]
Fixed with 3a7f49f6241f41d60549f70f3118b45d8eca9ed9 using callbacks
