### ISSUE TITLE
icloud photo library

### ISSUE THREAD

**Issue by armandsavotins** [fulldecent/FDTake#68]
I have a problem to save videos and photos to iCloud enabled Photo library. Is some ready solution out there?

**Comment by fulldecent** [comment]
Could you please explain further and include screenshots?

**Comment by fulldecent** [comment]
There has been a huge commit to master.

Could you please help review if this is still an issue now.

**Comment by fulldecent** [comment]
Closing now, please reopen if further details are available and this is not working on latest version
