### ISSUE TITLE
iOS 9: Black screen when taking the picture (even if user agreed)

### ISSUE THREAD

**Issue by frranck** [fulldecent/FDTake#71]
First I can see the camera, working  then i push the "click" button and get a dark screen, even if the user agreed. 
I get the following errors in the console (4 times):

CGAffineTransformInvert: singular matrix.
CGAffineTransformInvert: singular matrix.
CGAffineTransformInvert: singular matrix.
CGAffineTransformInvert: singular matrix.

**Comment by frranck** [comment]
ps: I'm creating the objects in the main queue.

**Comment by frranck** [comment]
http://stackoverflow.com/questions/34132933/uiimagepickercontroller-not-picking-image-in-ios-9

**Comment by fulldecent** [comment]
There has been a huge refactor in master. Could you please confirm if this is still an issue.

**Comment by frranck** [comment]
@fulldecent Couldn't test it; got a "higher minimum deployment target" issue on my project; would be great to fix it like in 'ActionSheetPicker-3.0', '~> 1.0' in a 0.2.6 version and then move to a 0.3.0...

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 80000

@interface MyPopoverController : UIPopoverController <UIAdaptivePresentationControllerDelegate>
@end

@implementation MyPopoverController
+ (BOOL)canShowPopover {
    if (IS_IPAD) {
        if ([UITraitCollection class]) {
            UITraitCollection *traits = [UIApplication sharedApplication].keyWindow.traitCollection;
            if (traits.horizontalSizeClass == UIUserInterfaceSizeClassCompact)
                return NO;
        }
        return YES;
    }
    return NO;
}

- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController *)controller traitCollection:(UITraitCollection *)traitCollection {
    return UIModalPresentationNone;
}
@end

#else

@interface MyPopoverController:UIPopoverController
@end

@implementation MyPopoverController
+(BOOL)canShowPopover {
    return IS_IPAD;
}
@end

#endif

**Comment by fulldecent** [comment]
Closing now, please reopen if further details are available and this is confirmed not working on the latest version
