### ISSUE TITLE
Module deployment target issue

### ISSUE THREAD

**Issue by grantkemp** [fulldecent/FDTake#81]
HI When I have tried to build using Cocoapods, 
I have set my build target to 8.0 but I get this error when trying to build: 
```Module file's minimum deployment target is ios8.0 v8.0: ```

Any ideas how to resolve?

**Comment by fulldecent** [comment]
I am not sure, but I am pretty confident that this is an issue with CocoaPods. I have seen the same thing with another Pod I was using.

The solution was to change the target api but for other targets I had (like UI Tests).

**Comment by grantkemp** [comment]
Looks like its working partially - I now only get an issue reported about XCode unable to find FDTakeDelegate. Its an older codebase - was this deprecated?

**Comment by fulldecent** [comment]
Yes, the API update did away with that. Please use these callbacks:

    /// A photo was selected
    public var didGetPhoto: ((photo: UIImage, info: [NSObject : AnyObject]) -> Void)?
    
    /// A video was selected
    public var didGetVideo: ((video: NSURL, info: [NSObject : AnyObject]) -> Void)?
    
    /// The user selected did not attempt to select a photo
    public var didDeny: (() -> Void)?
    
    /// The user started selecting a photo or took a photo and then hit cancel
    public var didCancel: (() -> Void)?
    
    /// A photo or video was selected but the ImagePicker had NIL for EditedImage and OriginalImage
    public var didFail: (() -> Void)?

**Comment by grantkemp** [comment]
Fab - Thanks for the quick response.
