### ISSUE TITLE
Swift 3 Migration

### ISSUE THREAD

**Issue by JettF** [fulldecent/FDTake#98]
Any idea on when this library will be converted to Swift 3?

**Comment by fulldecent** [comment]
Thank you. I am having trouble getting CocoaPods to work with Xcode 8. Which is giving me trouble in updating this project to Swift 3.

But I am working on this and seeking help!

**Comment by JettF** [comment]
Thanks for getting back to me. I will help if I can. What seems to be the problem? Are you using the Xcode 8 GM seed? Which version of CocoaPods do you have?

**Comment by fulldecent** [comment]
I have just put together documentation of how to make a Xcode project for Swift 3 modules.

This documentation is at https://github.com/fulldecent/swift-package. I am testing that it works and then plan on implementing that layout and all new Swift 3 syntax (with a major version bump) for this project.

If you have any advice on that project I will see that first. Thanks for helping out! I am using the released CocoaPods 1.0.1, not the prerelease one. Xcode is version 8.

**Comment by LivioGama** [comment]
I don't understand because even with `Use Legacy Swift Language Version`setting, the project doesn't compile in Xcode 8
![capture d ecran 2016-09-14 a 11 24 22](https://cloud.githubusercontent.com/assets/6930498/18506790/da37e678-7a6d-11e6-8b63-c70d5cbf6f40.png)

**Comment by fulldecent** [comment]
Working on this now at https://github.com/fulldecent/FDTake/pull/99

Live stream and collaboration at https://www.youtube.com/watch?v=nkGIlDStD7Q

**Comment by fulldecent** [comment]
Fixed in https://github.com/fulldecent/FDTake/commit/a144638e7c18dda469c36b24bee8536c2492cf54.

Known issue. I cannot get localization to work in Swift 3.0. Requesting assistance.
